[package]
name = "longport-python-macros"
version = "1.0.38"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "2.0.77", features = [] }
darling = "0.20.10"
thiserror = "1.0.29"
