language = "c"
include_guard = "_LONGBRIDGE_H_"
documentation_style = "doxy"
cpp_compat = true

[export.rename]
"CHttpClient" = "lb_http_client_t"
"CHttpResult" = "lb_http_result_t"
"CLanguage" = "lb_language_t"
"CMarket" = "lb_market_t"
"CDecimal" = "lb_decimal_t"
"CAsyncCallback" = "lb_async_callback_t"
"CAsyncResult" = "lb_async_result_t"
"CError" = "lb_error_t"
"CConfig" = "lb_config_t"
"CSubscription" = "lb_subscription_t"
"CPushQuote" = "lb_push_quote_t"
"CPushDepth" = "lb_push_depth_t"
"CPushBrokers" = "lb_push_brokers_t"
"CTradeSession" = "lb_trade_session_t"
"CTradeStatus" = "lb_trade_status_t"
"CTradeDirection" = "lb_trade_direction_t"
"COptionDirection" = "lb_option_direction_t"
"COptionType" = "lb_option_type_t"
"CWarrantType" = "lb_warrant_type_t"
"CAdjustType" = "lb_adjust_type_t"
"CPeriod" = "lb_period_t"
"CDepth" = "lb_depth_t"
"CBrokers" = "lb_brokers_t"
"CTrade" = "lb_trade_t"
"CPushTrades" = "lb_push_trades_t"
"CCandlestick" = "lb_candlestick_t"
"CPushCandlestick" = "lb_push_candlestick_t"
"COnQuoteCallback" = "lb_quote_callback_t"
"COnDepthCallback" = "lb_depth_callback_t"
"COnBrokersCallback" = "lb_brokers_callback_t"
"COnTradesCallback" = "lb_trades_callback_t"
"COnCandlestickCallback" = "lb_candlestick_callback_t"
"CQuoteContext" = "lb_quote_context_t"
"CSecurityStaticInfo" = "lb_security_static_info_t"
"CPrePostQuote" = "lb_prepost_quote_t"
"CSecurityQuote" = "lb_security_quote_t"
"COptionQuote" = "lb_option_quote_t"
"CDate" = "lb_date_t"
"CTime" = "lb_time_t"
"CWarrantQuote" = "lb_warrant_quote_t"
"CSecurityDepth" = "lb_security_depth_t"
"CSecurityBrokers" = "lb_security_brokers_t"
"CParticipantInfo" = "lb_participant_info_t"
"CIntradayLine" = "lb_intraday_line_t"
"CStrikePriceInfo" = "lb_strike_price_info_t"
"CIssuerInfo" = "lb_issuer_info_t"
"CTradingSessionInfo" = "lb_trading_session_info_t"
"CMarketTradingSession" = "lb_market_trading_session_t"
"CMarketTradingDays" = "lb_market_trading_days_t"
"CCapitalFlowLine" = "lb_capital_flow_line_t"
"CCapitalDistributionResponse" = "lb_capital_distribution_response_t"
"CCapitalDistribution" = "lb_capital_distribution_t"
"CRealtimeQuote" = "lb_realtime_quote_t"
"CTradeContext" = "lb_trade_context_t"
"CTopicType" = "lb_topic_type_t"
"COrderSide" = "lb_order_side_t"
"COrderType" = "lb_order_type_t"
"COrderStatus" = "lb_order_status_t"
"COrderTag" = "lb_order_tag_t"
"CTriggerStatus" = "lb_trigger_status_t"
"COutsideRTH" = "lb_outside_rth_t"
"CTimeInForceType" = "lb_time_in_force_type_t"
"COnOrderChangedCallback" = "lb_order_changed_callback_t"
"CPushOrderChanged" = "lb_push_order_changed_t"
"CExecution" = "lb_execution_t"
"CGetHistoryExecutionsOptions" = "lb_get_history_executions_options_t"
"CGetTodayExecutionsOptions" = "lb_get_today_executions_options_t"
"COrder" = "lb_order_t"
"CGetHistoryOrdersOptions" = "lb_get_history_orders_options_t"
"CGetTodayOrdersOptions" = "lb_get_today_orders_options_t"
"CReplaceOrderOptions" = "lb_replace_order_options_t"
"CSubmitOrderOptions" = "lb_submit_order_options_t"
"CCashInfo" = "lb_cash_info_t"
"CAccountBalance" = "lb_account_balance_t"
"CCashFlowDirection" = "lb_cash_flow_direction_t"
"CCashFlow" = "lb_cash_flow_t"
"CBalanceType" = "lb_balance_type_t"
"CCommissionFreeStatus" = "lb_commission_free_status_t"
"CDeductionStatus" = "lb_deduction_status_t"
"CChargeCategoryCode" = "lb_charge_category_code_t"
"CGetCashFlowOptions" = "lb_get_cash_flow_options_t"
"CGetFundPositionsOptions" = "lb_get_fund_positions_options_t"
"CFundPositionsResponse" = "lb_fund_position_response_t"
"CFundPositionChannel" = "lb_fund_position_channel_t"
"CFundPosition" = "lb_fund_position_t"
"CGetStockPositionsOptions" = "lb_get_stock_positions_options_t"
"CStockPositionsResponse" = "lb_stock_position_response_t"
"CStockPositionChannel" = "lb_stock_position_channel_t"
"CStockPosition" = "lb_stock_position_t"
"CFreeUserDataFunc" = "lb_free_userdata_func_t"
"CSubmitOrderResponse" = "lb_submit_order_response_t"
"CWatchListGroup" = "lb_watch_list_group_t"
"CWatchListSecurity" = "lb_watch_list_security_t"
"CMarginRatio" = "lb_margin_ratio_t"
"CSecurityBoard" = "lb_security_board_t"
"COrderHistoryDetail" = "lb_order_history_detail_t"
"COrderChargeFee" = "lb_order_charge_fee_t"
"COrderChargeItem" = "lb_order_charge_item_t"
"COrderChargeDetail" = "lb_order_charge_detail_t"
"COrderDetail" = "lb_order_detail_t"
"CEstimateMaxPurchaseQuantityOptions" = "lb_estimate_max_purchase_quantity_options_t"
"CEstimateMaxPurchaseQuantityResponse" = "lb_estimate_max_purchase_quantity_response_t"

[export]
include = [
    "CSubscription",
    "CSecurityStaticInfo",
    "CSecurityQuote",
    "COptionQuote",
    "CWarrantQuote",
    "CSecurityDepth",
    "CSecurityBrokers",
    "CParticipantInfo",
    "CIntradayLine",
    "CStrikePriceInfo",
    "CIssuerInfo",
    "CTradingSessionInfo",
    "CMarketTradingSession",
    "CMarketTradingDays",
    "CCapitalFlowLine",
    "CCapitalDistributionResponse",
    "CRealtimeQuote",
    "CExecution",
    "COrder",
    "CAccountBalance",
    "CCashFlow",
    "CFundPositionsResponse",
    "CStockPositionsResponse",
    "CSubmitOrderResponse",
    "CWatchListGroup",
    "CWatchListSecurity",
    "CMarginRatio",
    "COrderDetail",
    "CEstimateMaxPurchaseQuantityResponse",
]
