[package]
name = "longport-nodejs-macros"
version = "1.1.7"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "2.0.77", features = [] }
thiserror = "1.0.29"
convert_case = "0.6.0"
