[tasks.java]
command = "cargo"
args = ["build", "-p", "longport-java"]

[tasks.javah]
args = [
  "--release",
  "8",
  "-h",
  "c",
  "-cp",
  "libs/native-lib-loader-2.4.0.jar;libs/slf4j-api-1.7.30.jar;libs/gson-2.10.1.jar",
  "-sourcepath",
  "javasrc/src/main/java",
  "-d",
  "classes",
  "javasrc/src/main/java/com/longport/SdkNative.java",
]
command = "javac"
cwd = "java"

[tasks.compile-java-test]
args = [
  "--release",
  "8",
  "-cp",
  "libs/native-lib-loader-2.4.0.jar;libs/slf4j-api-1.7.30.jar;libs/gson-2.10.1.jar",
  "-sourcepath",
  "javasrc/src/main/java",
  "-d",
  "classes",

  "javasrc/src/main/java/com/longport/AsyncCallback.java",
  "javasrc/src/main/java/com/longport/Config.java",
  "javasrc/src/main/java/com/longport/ConfigBuilder.java",
  "javasrc/src/main/java/com/longport/Language.java",
  "javasrc/src/main/java/com/longport/Market.java",
  "javasrc/src/main/java/com/longport/OpenApiException.java",
  "javasrc/src/main/java/com/longport/SdkNative.java",
  "javasrc/src/main/java/com/longport/AsyncCallback.java",

  "javasrc/src/main/java/com/longport/HttpClient.java",

  "javasrc/src/main/java/com/longport/quote/AdjustType.java",
  "javasrc/src/main/java/com/longport/quote/Brokers.java",
  "javasrc/src/main/java/com/longport/quote/BrokersHandler.java",
  "javasrc/src/main/java/com/longport/quote/Candlestick.java",
  "javasrc/src/main/java/com/longport/quote/CandlestickHandler.java",
  "javasrc/src/main/java/com/longport/quote/CapitalDistribution.java",
  "javasrc/src/main/java/com/longport/quote/CapitalDistributionResponse.java",
  "javasrc/src/main/java/com/longport/quote/CapitalFlowLine.java",
  "javasrc/src/main/java/com/longport/quote/Depth.java",
  "javasrc/src/main/java/com/longport/quote/DepthHandler.java",
  "javasrc/src/main/java/com/longport/quote/DerivativeType.java",
  "javasrc/src/main/java/com/longport/quote/IntradayLine.java",
  "javasrc/src/main/java/com/longport/quote/IssuerInfo.java",
  "javasrc/src/main/java/com/longport/quote/MarketTradingDays.java",
  "javasrc/src/main/java/com/longport/quote/MarketTradingSession.java",
  "javasrc/src/main/java/com/longport/quote/OptionDirection.java",
  "javasrc/src/main/java/com/longport/quote/OptionQuote.java",
  "javasrc/src/main/java/com/longport/quote/OptionType.java",
  "javasrc/src/main/java/com/longport/quote/ParticipantInfo.java",
  "javasrc/src/main/java/com/longport/quote/Period.java",
  "javasrc/src/main/java/com/longport/quote/PrePostQuote.java",
  "javasrc/src/main/java/com/longport/quote/PushBrokers.java",
  "javasrc/src/main/java/com/longport/quote/PushCandlestick.java",
  "javasrc/src/main/java/com/longport/quote/PushDepth.java",
  "javasrc/src/main/java/com/longport/quote/PushQuote.java",
  "javasrc/src/main/java/com/longport/quote/PushTrades.java",
  "javasrc/src/main/java/com/longport/quote/QuoteContext.java",
  "javasrc/src/main/java/com/longport/quote/QuoteHandler.java",
  "javasrc/src/main/java/com/longport/quote/RealtimeQuote.java",
  "javasrc/src/main/java/com/longport/quote/SecurityBoard.java",
  "javasrc/src/main/java/com/longport/quote/SecurityBrokers.java",
  "javasrc/src/main/java/com/longport/quote/SecurityDepth.java",
  "javasrc/src/main/java/com/longport/quote/SecurityQuote.java",
  "javasrc/src/main/java/com/longport/quote/SecurityStaticInfo.java",
  "javasrc/src/main/java/com/longport/quote/StrikePriceInfo.java",
  "javasrc/src/main/java/com/longport/quote/SubFlags.java",
  "javasrc/src/main/java/com/longport/quote/Subscription.java",
  "javasrc/src/main/java/com/longport/quote/Trade.java",
  "javasrc/src/main/java/com/longport/quote/TradeDirection.java",
  "javasrc/src/main/java/com/longport/quote/TradeSession.java",
  "javasrc/src/main/java/com/longport/quote/TradeStatus.java",
  "javasrc/src/main/java/com/longport/quote/TradesHandler.java",
  "javasrc/src/main/java/com/longport/quote/TradingSessionInfo.java",
  "javasrc/src/main/java/com/longport/quote/WarrantQuote.java",
  "javasrc/src/main/java/com/longport/quote/WarrantType.java",
  "javasrc/src/main/java/com/longport/quote/WatchlistGroup.java",
  "javasrc/src/main/java/com/longport/quote/CalcIndex.java",
  "javasrc/src/main/java/com/longport/quote/SecurityCalcIndex.java",
  "javasrc/src/main/java/com/longport/quote/WatchlistSecurity.java",
  "javasrc/src/main/java/com/longport/quote/CreateWatchlistGroup.java",
  "javasrc/src/main/java/com/longport/quote/CreateWatchlistGroupResponse.java",
  "javasrc/src/main/java/com/longport/quote/DeleteWatchlistGroup.java",
  "javasrc/src/main/java/com/longport/quote/UpdateWatchlistGroup.java",

  "javasrc/src/main/java/com/longport/trade/AccountBalance.java",
  "javasrc/src/main/java/com/longport/trade/BalanceType.java",
  "javasrc/src/main/java/com/longport/trade/CashFlow.java",
  "javasrc/src/main/java/com/longport/trade/CashFlowDirection.java",
  "javasrc/src/main/java/com/longport/trade/CashInfo.java",
  "javasrc/src/main/java/com/longport/trade/Execution.java",
  "javasrc/src/main/java/com/longport/trade/FundPosition.java",
  "javasrc/src/main/java/com/longport/trade/FundPositionChannel.java",
  "javasrc/src/main/java/com/longport/trade/FundPositionsResponse.java",
  "javasrc/src/main/java/com/longport/trade/GetCashFlowOptions.java",
  "javasrc/src/main/java/com/longport/trade/GetFundPositionsOptions.java",
  "javasrc/src/main/java/com/longport/trade/GetHistoryExecutionsOptions.java",
  "javasrc/src/main/java/com/longport/trade/GetHistoryOrdersOptions.java",
  "javasrc/src/main/java/com/longport/trade/GetStockPositionsOptions.java",
  "javasrc/src/main/java/com/longport/trade/GetTodayExecutionsOptions.java",
  "javasrc/src/main/java/com/longport/trade/GetTodayOrdersOptions.java",
  "javasrc/src/main/java/com/longport/trade/MarginRatio.java",
  "javasrc/src/main/java/com/longport/trade/Order.java",
  "javasrc/src/main/java/com/longport/trade/OrderChangedHandler.java",
  "javasrc/src/main/java/com/longport/trade/OrderSide.java",
  "javasrc/src/main/java/com/longport/trade/OrderStatus.java",
  "javasrc/src/main/java/com/longport/trade/OrderTag.java",
  "javasrc/src/main/java/com/longport/trade/OrderType.java",
  "javasrc/src/main/java/com/longport/trade/OutsideRTH.java",
  "javasrc/src/main/java/com/longport/trade/PushOrderChanged.java",
  "javasrc/src/main/java/com/longport/trade/ReplaceOrderOptions.java",
  "javasrc/src/main/java/com/longport/trade/StockPosition.java",
  "javasrc/src/main/java/com/longport/trade/StockPositionChannel.java",
  "javasrc/src/main/java/com/longport/trade/StockPositionsResponse.java",
  "javasrc/src/main/java/com/longport/trade/SubmitOrderOptions.java",
  "javasrc/src/main/java/com/longport/trade/SubmitOrderResponse.java",
  "javasrc/src/main/java/com/longport/trade/TimeInForceType.java",
  "javasrc/src/main/java/com/longport/trade/TopicType.java",
  "javasrc/src/main/java/com/longport/trade/TradeContext.java",
  "javasrc/src/main/java/com/longport/trade/TriggerStatus.java",
  "javasrc/src/main/java/com/longport/trade/CommissionFreeStatus.java",
  "javasrc/src/main/java/com/longport/trade/DeductionStatus.java",
  "javasrc/src/main/java/com/longport/trade/ChargeCategoryCode.java",
  "javasrc/src/main/java/com/longport/trade/OrderHistoryDetail.java",
  "javasrc/src/main/java/com/longport/trade/OrderChargeFee.java",
  "javasrc/src/main/java/com/longport/trade/OrderChargeItem.java",
  "javasrc/src/main/java/com/longport/trade/OrderChargeDetail.java",
  "javasrc/src/main/java/com/longport/trade/OrderDetail.java",

  "test/Main.java",
]
command = "javac"
cwd = "java"

[tasks.test-java]
command = "java"
args = [
  "-Djava.library.path=target/debug",
  "-cp",
  "java/classes;java/libs/native-lib-loader-2.4.0.jar;java/libs/slf4j-api-1.7.30.jar;java/libs/gson-2.10.1.jar",
  "Main",
]
dependencies = ["java", "compile-java-test"]
