[package]
edition = "2021"
name = "longbridge-proto"
version = "0.2.9"
description = "Longbridge Protocol"
license = "MIT OR Apache-2.0"

[dependencies]
prost = "0.10.3"

[build-dependencies]
prost-build = "0.10.3"
