[package]
edition = "2021"
name = "longport-candlesticks"
version = "1.0.6"
description = "LongPort candlestick utils for Rust"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "2.4.1"
rust_decimal = "1.25.0"
time = { version = "0.3.10", features = ["macros"] }
time-tz = "1.0.2"
