[package]
edition = "2021"
name = "longbridge-candlesticks"
version = "0.2.29"
description = "Longbridge candlestick utils for Rust"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1.3.2"
rust_decimal = "1.25.0"
time = { version = "0.3.10", features = ["macros"] }
time-tz = "1.0.2"
