[package]
name = "longbridge-java-macros"
version = "0.2.48"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
darling = "0.14.0"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "1.0.77", features = ["parsing"] }
thiserror = "1.0.29"
