name: Issue Notify
on:
  issues:
    types: [opened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              ${{ github.event.issue.title }} #${{ github.event.issue.number }}

              ${{ github.event.issue.html_url }}
